### ISSUE TITLE
How do I use the trainer? Still got keyerror. 

### ISSUE THREAD

**Issue by gordonhu608** [gaopengcuhk/CLIP-Adapter#5]
I think when using coop's style, all I need is to put the clip_adapter file into the trainer's directory. Doesn't using @TRAINER_REGISTRY.register() automatically detect the name? 
So why would I get this error KeyError: 'Object name "CLIP_Adapter" does not exist in "TRAINER" registry'

**Comment by AshleyLuo001** [comment]
Did you solve this problem? I had this problem too.
